### ISSUE TITLE
학생 답안지 점수 출력 (더 알아보기)

### ISSUE THREAD

**Issue by difflzkzk** [goodee-project/LMS-Y#3]
학생답안지 점수 출력 더알아보기
문자열 구분 if/ 하나의 기준으로 나누는 choose
https://github.com/goodee-project/LMS-Y/blob/d1dbf11d39e41d0c8d21649c3f1db3ec2fd08aba/lms/src/main/java/gd/fintech/lms/student/mapper/AnswerSheetMapper.xml#L10-L16

**Comment by 1F24DCA** [comment]
MultipleChoice 테이블에 score 컬럼을 추가함에 따라서 필요없는 고민으로 추정, 이슈 해결
